steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "us.gcr.io/$_PROJECT_NAME/$_CONTAINER_NAME:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us.gcr.io/$_PROJECT_NAME/$_CONTAINER_NAME:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud compute ssh $_USER@$_VM_NAME \
        --project=$_PROJECT_NAME \
        --zone=$_ZONE \
        --command="docker stop \$(docker ps -q) \
                    && docker rm \$(docker ps -a -q) \
                    && docker rmi \$(docker images -q) \
                    && docker pull us.gcr.io/$_PROJECT_NAME/$_CONTAINER_NAME:latest \
                    && docker run -d -p 3000:3000 us.gcr.io/$_PROJECT_NAME/$_CONTAINER_NAME:latest"

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
